### ISSUE TITLE
cmake doesn't find  wxWidgets or pdfium

### ISSUE THREAD

**Issue by trogmaniac** [TcT2k/wxPDFView#1]
I can't make cmake find either wxWidgets or pdfium. Which conditions must be met so that cmake finds them?

I already built both wxWidgets and pdfium successfully,

I tried setting the environment variables "PDFIUM_ROOT_DIR" and "wxWidgets_ROOT_DIR", but that didn't change anything.

**Comment by trogmaniac** [comment]
I got it to work:

a) CMake doesn't know about the wxWidgets development version which is version 3.1.x. With wxWidgets 3.0.2 it worked

b) I manually entered the pdfium directory into FindPDFium.cmake and it worked.

**Comment by TcT2k** [comment]
Good that you got it to work. But just for future reference when you invoke
cmake you can specify variables like cmake -DPDFIUM_ROOT_DIR=path/to/pdfium
or you can use the cmake GUI.

Which platform are you building for?

2015-09-10 20:35 GMT+02:00 trogmaniac notifications@github.com:
