### ISSUE TITLE
compile issue 

### ISSUE THREAD

**Issue by rodingbao** [TcT2k/wxPDFView#12]
cmake 3.26 +TDM GCC 9.2+ prebuilt pdfium binaries (version 113.0.5664.0)

compile terminate with following message, is there mistake in souce code? 
I didnt find fpdf_libs.h in folder "include " of prebuilt pdfium binaries

[  7%] Building CXX object CMakeFiles/wxPDFView.dir/src/PDFView.cpp.obj
[ 14%] Building CXX object CMakeFiles/wxPDFView.dir/src/PDFViewImpl.cpp.obj
D:\Coding\lib\wxPDFView\src\PDFViewImpl.cpp:21:10: fatal error: fpdf_libs.h: No such file or directory
   21 | #include "fpdf_libs.h"
      |          ^~~~~~~~~~~~~
compilation terminated.

![image](https://user-images.githubusercontent.com/119423811/231976066-70125ffd-4eb4-4207-918c-694b174f8dfc.png)

**Comment by camzmac** [comment]
I am having a similar problem:

```
wxPDFView-master/src/PDFViewImpl.cpp:21:10: fatal error: fpdf_libs.h: No such file or directory
   21 | #include "fpdf_libs.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:38: PDFViewImpl.o] Error 1
```

I was unable to find fpdf_libs.h in the pdfium sources, either.
