### ISSUE TITLE
wxPDFView doesn't build with latest pdfium

### ISSUE THREAD

**Issue by trogmaniac** [TcT2k/wxPDFView#2]
First, the location and names of some pdfium files have changed. E.g. "fpdfdoc.h" is now "fpdf_doc.h" and lies in <pdfium>/public/. This was something i could fix locally.

But then it creates several compiler errors with are very likely caused by changes in pdfium, which i couldn't fix by myself because they'd require internal knowledge about pdfium.

I hope you'll be able to update wxPDFView to work with the latest pdfium version, i'd really like to use it.

**Comment by TcT2k** [comment]
Which platform you are building on?

I'll probably look into newer version, but in the mean time you could give it a try with pdfium revision 2118.

**Comment by trogmaniac** [comment]
Sorry for not mentioning that, i'm under Windows. It took me two days to build pdfium because their build instructions are so horribly wrong. I don't think i want to go through that again.

I'd rather try to adjust wxPDFView :)

**Comment by TcT2k** [comment]
Yeah building pdfium is not that easy (and it was even harder).

If you get it build with the recent pdfium any PR is welcome. I can't promise when I'll be able to look into it, but I'm definitely interested.

**Comment by trogmaniac** [comment]
I think i got it to work. Most changes except two were straight forward. I'm not sure about the two code locations with the (CPDF_Action *) casts. You should check those.

Here are two diff files, one for the code, the other one for FindPDFium.cmake. I'm sure there are more elegant ways to do this, but i'm a GIT noob.

http://pastebin.com/n2S81g8C
http://pastebin.com/sDk2yFRt

And BTW: Thanks for wxPDFView, this is great stuff and will be very useful.

**Comment by TcT2k** [comment]
Thank you very much for the patches. Looks good to me. I've applied them.

Diffs from pastebin are easy enough to merge, but have a look at https://help.github.com/articles/using-pull-requests/ how to create a pull request. If you have done it once it's pretty easy and makes it even easier for the author to merge the changes.

**Comment by trogmaniac** [comment]
Thanks, i'll look into that.

Some additional information i forgot:
a) I was using VS2013, but 32bit builds only. I hope the changes still work on other platforms/compiler.

b) I could't find what the current pdfium version number is, so i just wrote "latest version".
