### ISSUE TITLE
Direct Printing?

### ISSUE THREAD

**Issue by mtangoo** [TcT2k/wxPDFView#3]
Thanks for taking time to make this library. My question is, can I do direct printing of opened document?
Thanks

**Comment by TcT2k** [comment]
I'm not sure what you mean by direct printing? You can call the `wxPDFView::Print()` which will handle the complete printing process (Dialog + Printing) or if you need more control over the print process you could use `wxPDFView::CreatePrintout()`.

**Comment by mtangoo** [comment]
I could not find it in docs. I want to send pdf to printer with some settings, no dialog at all

**Comment by TcT2k** [comment]
Have a look at `wxPDFViewPanel::StartPrint` https://github.com/TcT2k/wxPDFView/blob/master/src/PDFViewDocumentPanel.cpp#L573
If I'm not mistaken you could take that code and modify the `wxPrinter::Print()`call to set `prompt = false` and it should not display the print dialog and you should be able to modify print parameters in `wxPrintDalogData`.
If you need even deeper customization I would suggest looking into the `wxPDFViewPrintout` implementation.

**Comment by mtangoo** [comment]
Thanks for the pointer
